import { Jost } from 'next/font/google'
import { Kumbh_Sans } from 'next/font/google'
import './globals.css'

const jost = Jost({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-jost'})

const kumbhSans = Kumbh_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-kumbh-sans'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${kumbhSans.variable} antialiased`} // Aplique as fontes aqui
      >
        {children}
      </body>
    </html>
  )
}
